### ISSUE TITLE
Server UI: New feature, assignment of one of two ringtones for an experiment.

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1009]
We now have two ringtones available for an experiment, the awesome bark, and a 1970's pbs sounding tone for cultures that might be offended or annoyed by dog barking. We have this on the experiment definition but need to have a way to define which tone is used in the server ui.

The Paco Bark should be the default.

The other option is the Paco Alternate Alert Tone. 

It is assigned onto the experiment field,  ringtoneUri. It should take on the values:
/assets/ringtone/<RingtoneName>,
where RingtoneName is "Paco Bark" or "Paco Alternate Alert Tone".

**Comment by ianspiro** [comment]
To clarify-- so the values should be:

/assets/ringtone/Paco Bark
/assets/ringtone/Paco Alternate Alert Tone

?

**Comment by BobEvans** [comment]
Yes

**Comment by ianspiro** [comment]
Where should this go in the UI? I was thinking under advanced but that's for groups. We don't have a good place to put experiment-level settings atm.
