### ISSUE TITLE
Web UI: Action editor popup should be resizable

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1010]
In general, any popup screen should be resizable to avoid keyhole problems, but this one particularly needs to be resizable given that it allows edit of scripts which might be lengthy.

Perhaps create separate bugs for other popups that need to be resized so that we can track them even if we don't do them now.

**Comment by ianspiro** [comment]
I'm looking into this and it seems that ACE has no built-in way to support user resizing, only auto. I currently have the editor set to default to 10 lines and expand to as many as 20. So typing extra lines of code will expand the height of the editor. I could increase the 20. Another possibility would be some kind of toggle for some of the dialogs that expands them into a fullscreen mode.

**Comment by BobEvans** [comment]
Make it wider and taller
