### ISSUE TITLE
Web UI: Default times for daily and other fixed-times schedules should be 12pm instead of 12am

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1016]
This is low-priority, but, it would be nice to have the current hour be the time when a user creates any of the fixed time schedules. So, round to the nearest hour, forwards. 

This puts it close (edit-wise) to when they will probably be testing it on themselves and allows them to do less work. Also, it most likely puts the AM/PM section in the correct place causing even less editing.

**Comment by ianspiro** [comment]
change default to noon
