### ISSUE TITLE
Server UI: Mark iOS incompatible options

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1017]
We previously had marked iOS incompatible options on the experiment builder screens so that users would understand that things did not work.

Given that it will be a few months for the updated iOS client and that there will always be things that the iOS version can't do, we should mark any features that are incompatible now to help users in the meantime.

Off the top of my head, this includes 
adding multiple groups
Adding multiple schedules
adding Event triggers
Doing any action other than Sending a Notification to participate
Override form display
End of Day groups
Background listening
Recording phone details
Recording App Usage and browser history

Also, Contact Email and Organization are not yet shown on iOS.

Given how many features this is, we should have a discreet annotation that allows hover or clicking for more information. Perhaps the word iOS with a circle slash over it as a small icon would look acceptable.

**Comment by ianspiro** [comment]
Some explorations. Do you like any of these? I added a tooltip at the end. I'm thinking maybe the warning icon only shows when relevant features are enabled to clutter the UI less overall.

![no-ios-explore](https://cloud.githubusercontent.com/assets/9756028/9534635/c4e2cfa4-4cce-11e5-9da8-5de3193aab71.png)
![no-ios](https://cloud.githubusercontent.com/assets/9756028/9534636/c4e8baea-4cce-11e5-83e4-dad7f02d6c55.png)

**Comment by BobEvans** [comment]
I kind of like the one you used on paco staging. Though I wonder if the version with the bounding circle isn’t more clear?

I say go with what you’ve got it looks nice.
