### ISSUE TITLE
Web ui: Report Gen: Participation Stats Main page: Fake Data definition

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1066]
Define the data structure needed by this page that the server should return.

Also define query params to send and pagination.

**Comment by ianspiro** [comment]
GET /participation?experimentId=<experiment ID>&range=<number hours>&cursor=<optional cursor ID>

Pass in the experiment ID and optionally, a number of hours. Default is 24. Endpoint returns the total number of participants who have joined and a participant entry for each one. The participant entry includes their email address and the signal and response counts, both for the entire length of the experiment and for the recent range window. If there are too many results to return at once, the server may return a subset and a nextCursor value.

{
   count: <total joined participants>,
   participants: [ {
                            who: <email>,
                            recentSignalCount: <number>,
                            recentResponseCount: <number>,
                            totalSignalCount: <number>,
                            totalResponseCount: <number> } ],
   nextCursor: <null | cursor ID>
}

**Comment by BobEvans** [comment]
There is no user request for querying over a range. They want stats for today and the full duration so far on the this screen. 

After that, they want daily stats for each day of participation at a per-participant query.

There also needs to be a limit param which sets how many results are being requested.

Also, in the data for each participant, we need selfReportCountToday and selfReportCountTotal.

Here is a revised structure that reflects these changes:

{
count: ,
participants: [ {
who: ,
todaySignalCount: ,
todayResponseCount: ,
todaySelfReportCount: ,
totalSignalCount: ,
totalResponseCount: ,
todaySelfReportCount:} ],
nextCursor: 
}

**Comment by ianspiro** [comment]
Sure. I don't mean to add a new feature that we don't actually need. But say for the "daily stats for each day of participation at a per-participant query" couldn't we reuse the same endpoint, just specifying the range for a particular day? Or the endpoint returns these stats for each individual day all at once?

**Comment by BobEvans** [comment]
I was thinking that if a user was specified in the query, it would return all information for that user, instead of the short, population-level form that it will return when no user is specified.

So, this would be something along the lines of 

/participation?experimentId=&who=&limit=&cursor=

**Comment by BobEvans** [comment]
I have checked in the first version of this which tries to return the whole data set and pushed it to develop. Note: it does not currently honor limit or cursor parameters.
