### ISSUE TITLE
web ui: add form for post join instructions html

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1070]
After a user joins an experiment, they are now presented with a page that confirms this, offers them researcher provided instructions, and, if applicable allows them to jump to review the schedule, set the Lollipop process monitoring, check their ringer volume, and in the future, configure external sensors, like Kitkat steps, Jawbone, fitbit, etc..

The property on experiment, at the top level, is postInstallInstructions. 

The ui, probably on the basics page, should offer a form to enter these instructions.

Ideally, it would be an html editor, like Ace, since they can enter html.

**Comment by ianspiro** [comment]
Why is the server sticking this boilerplate in? "<b>You have successfully joined the experiment!....." Shouldn't that be client-side? Null could trigger some default. It would be nice if the snippet included some \n's as well.

**Comment by BobEvans** [comment]
This was because the client was not creating it previously. 

On new experiments, initiated from the client side now, we can put this basic version in, as you added in the CL. Thanks for adding \n too.
