### ISSUE TITLE
nameOfClass appears in experiment definition

### ISSUE THREAD

**Issue by ianspiro** [google/paco#1071]
Seems to happen on the server side. It shows up once for each object. Is this WAI?

**Comment by BobEvans** [comment]
This is new you are right and yes working as intended.

This type information is used by the iOS client to automatically determine how to deserialize the json stream into appropriate the classes. It is a non-jackson-specific way to deal with the subtypes in the stream.

**Comment by ianspiro** [comment]
Should I consider stripping those fields from the web source view? (I'm assuming the server will add it back if missing.) Seems like a user could edit it and cause weirdness.

**Comment by BobEvans** [comment]
Not right now. The user’s edits will not be propagated because it is a computed method with no field backing it.
