### ISSUE TITLE
web ui: Deleting an experiment should refresh the admin list

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1077]
Currently, the experiment still shows up after the user agrees to deleting an experiment,

**Comment by ianspiro** [comment]
Pretty sure the latest version does this. Can you confirm?

**Comment by BobEvans** [comment]
OK, it works. I had to wait a long time though given the vast number of experiments I have. So, will close as working

**Comment by ianspiro** [comment]
I had added a subtle affordance where the deleted experiment grays out
right away so the user doesn't try to click it again.

**Comment by BobEvans** [comment]
Might this explain why a lot of experiments are now greyed out on the admin
list?
