### ISSUE TITLE
web ui: data screen - expand width to ~90% of screen width

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1109]
The data view is very constrained for actually looking at data. On a large monitor, it would be nice if it expands to fill almost all of the width so data is more easily viewed. Maybe 90% or 95%? We still want it to look nice. 

There is a larger problem here is that, on a long data set, scrolling with a traditional mouse requires the user to go to the bottom of the data set (maybe many pages down) to where the scroll bar is to horizontally scroll. If it were full-bleed, the user would always have the scrollbar in the browser available without having to lose their vertical place.

This goes for any other report page as well.

**Comment by BobEvans** [comment]
I will put the second paragraph in a new issue since it will probably take more time to solve than just using more width.

**Comment by ianspiro** [comment]
The data viewer expands to fill the entire width minus 16px on either side. Why 90%?
