### ISSUE TITLE
Web ui: editing-then-save in source window does not refresh experiment after save

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1119]
Edit an existing experiment in the source tab.
Hit save.
make another edit.
hit save.

expected: the source was updated with latest version and was save-able in future edits.
actual: the server returns an error that there is a newer version of the experiment.

**Comment by ianspiro** [comment]
I'm having trouble reproducing this

**Comment by ianspiro** [comment]
Oh, just saw the detail about double saving. Now I can repro.
