### ISSUE TITLE
Web UI: Report columns

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1136]
for csv, json, html data views

who (if multiple people queried), 
responseTime
ScheduledTime
(experimentId - if no experimentId in query then show)
ExperimentGroupName
responseVariable1
..
responseVariableN
ExperimentVersion
ActionTriggerId
ActionId
ActionTriggerSpecId
referredGroup (if exists in a group)
eodResponseTime (if exists in a group)
appId
pacoId

**Comment by ianspiro** [comment]
Should any columns be hidden?

**Comment by BobEvans** [comment]
That is second order. We can file a new issue for that.
