### ISSUE TITLE
iOS: log in improvement

### ISSUE THREAD

**Issue by yimingcheung** [google/paco#114]
- allow two step log in
https://github.com/google/paco/issues/922
- Considering using Google+ SDK:
https://developers.google.com/+/mobile/ios/
- allow log out
https://github.com/google/paco/issues/923
- allow switch account
https://github.com/google/paco/issues/924
- delay login until needed: https://github.com/google/paco/issues/740
- support offline 
- log in error handling properly: 
a. internet offline
b. user name and password are not correct
c. other error e.g. server down, etc.

**Comment by BobEvans** [comment]
fixed
