### ISSUE TITLE
Web ui: Sometimes scheduledTime or responseTime do not appear on list of columns

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1185]
They should always appear and always be checked by default.

**Comment by ianspiro** [comment]
Is scheduledTime the same as when? I currently don't turn on when by default. I don't see any data for scheduledTime.

**Comment by BobEvans** [comment]
They are different columns. 

“ScheduledTime" is present when Paco generates a signal according to some trigger. “When" is when the server receives data from the client. “When" is optional but “scheduledTime" is required for most researchers. 

To complete the discussion of time-related columns, responseTime is when the user responds (or doesn’t) and is also required for most researchers. Even if there is not data, it needs to be there just as scheduledTime. Researchers often use these to understand response patterns of participants as well as signaling patterns of their experiment.

Here is how researchers interpret these two fields in combination. 

			        responseTime   | scheduledTime   |  Meaning
                               -------------------------------------------------------------------------
			      |      X                  |       X                   | signaled response
                               -------------------------------------------------------------------------
			      |      X                  |                            | self report response
                               -------------------------------------------------------------------------
			      |                          |       X                   | missed response
                               -------------------------------------------------------------------------
