### ISSUE TITLE
Web UI: Specify timezone on Stats view

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1253]
When working with international participants, it is important to be able to look at stats relative to their date not the server time or local time. 
Allow specification of timezone for the stats report to use. 
Default to user's (browser's) local timezone,

the queryparam is tz and it expects the timezone id, e.g. America/Los Angeles.

**Comment by ianspiro** [comment]
Can you clarify- is this for the stats endpoint or the events endpoint? I'm passing in different values for tz to events and not seeing any difference in the data.

Do you envision a select with every possible timezone string? There are over 400. Seems like the primary use case is either user local time (tz=null ?) or researcher local time.

This feature will likely require an additional library for dealing with the timezone strings. JS can only determine UTC offset, not the zone name. So we'd need to get the offset then cross reference it with the names list.

**Comment by ianspiro** [comment]
I talked to Mike about this aspect of his most recent study and he says what the researchers and recruiters need most is the ability to see all stats relative to the participants' respective timezones. I am having trouble thinking of a case when the daily stats should be relative to some single, global timezone. If so, this means we don't need to add this selector to the UI, but instead update the way the backend computes the daily stats.

**Comment by BobEvans** [comment]
Interesting, so, this seems like it would be more “correct” for all cases. It also seems like it would also be confusing in the current UI because we would need to show each person’s timezone next to their particular stat. If we are going to do it this way, we should rope in a design resource.

So far, there have only been a few experiments run in widely divergent timezones. It certainly could happen, and this changes the meaning of the stats. For the most part, experiments have a fairly constrained set of timezones and they are adjacent to each other so that day computation against one time zone works out ok.

Picking a timezone to set the day for computing statistics was an easy-to-implement compromise that covered most cases we have seen so far. Mike, would being able to pick one timezone to use as the day for computing statistics have been useful to you on that study or do you think the more comprehensive solution is the minimum requirement?

Best,
Bob

**Comment by BobEvans** [comment]
We discussed this in person, and I don't think choosing a timezone in the
UI is really what admins are trying to do--experiments are designed to run
in participants' local time, so it makes sense to think about whether
they've done, say, their "Friday" task. It doesn't seem necessary to
retabulate the results in an arbitrary timezone.

On Fri, Nov 20, 2015 at 1:54 PM, Bob Evans <rbe5000@gmail.com> wrote:

> Interesting, so, this seems like it would be more “correct” for all cases.
> It also seems like it would also be confusing in the current UI because we
> would need to show each person’s timezone next to their particular stat. If
> we are going to do it this way, we should rope in a design resource.
>
> So far, there have only been a few experiments run in widely divergent
> timezones. It certainly could happen, and this changes the meaning of the
> stats. For the most part, experiments have a fairly constrained set of
> timezones and they are adjacent to each other so that day computation
> against one time zone works out ok.
>
> Picking a timezone to set the day for computing statistics was an
> easy-to-implement compromise that covered most cases we have seen so far.
> Mike, would being able to pick one timezone to use as the day for computing
> statistics have been useful to you on that study or do you think the more
> comprehensive solution is the minimum requirement?
>
> Best,
> Bob
>
> > On Nov 20, 2015, at 10:34 AM, ianspiro <notifications@github.com> wrote:
> >
> > I talked to Mike about this aspect of his most recent study and he says
> what the researchers and recruiters need most is the ability to see all
> stats relative to the participants' respective timezones. I am having
> trouble thinking of a case when the daily stats should be relative to some
> single, global timezone. If so, this means we don't need to add this
> selector to the UI, but instead update the way the backend computes the
> daily stats.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
>


-- 
Mike Brzozowski | User experience researcher | zozo@google.com
<https://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&to=zozo@google.com> |
 650-479-6960
Sent on desktop; please excuse the verbosity.

**Comment by BobEvans** [comment]
moved to server side calculation of stats based on user timezone.
