### ISSUE TITLE
Web UI: Contextual Help

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1284]
This has been turned into a milestone instead since it needs more clarity.

**Comment by mhadjimichael** [comment]
*Have you guys seen this (short) user guide?
https://docs.google.com/document/d/1TGoqurACcMUlTW6gVYP9skUrEEi9TIEP8uY1BHhrf68/edit?usp=sharing

**Comment by NickAraujo** [comment]
Thanks, Marios, this is a nice alternative.

Ian, the info icons seem reasonable if used *very* sparingly--otherwise, they feel like the nuclear option. I think we need to better understand the types of problems users encounter in order to design the appropriate level of support.

**Comment by BobEvans** [comment]
In the meantime, we at least need a link to the user manual on the page at all times.

I think one area that is definitely not clear is Extra Data Collection Declarations. That is always going to be opaque because it is advanced. Sometimes people check it because they misunderstand it.

I think as a general principle of figuring out where to offer help, we should keep in mind that this is an expert tool that will usually require some training to do anything other than the most basic stuff. So, let’s make sure they know where the training is and can get to it easily. 

One idea that just occurred to me about where to put help icons is that each tab should have an overview of what the tab is for, the Basics tab already does. Additionally, we can add a link to help at the end of that one liner that jumps into the help contents.

So, for the Group Tab, a sentence like, “This page is used to define moments for action, e.g. triggers, and what to do at those moments, e.g., notify the user to respond, and questions to ask the user.” This needs some word smithing, but, you get the idea. Then we either put a text link or the icon at the end to go to help.”

On the Admin tab, same thing, This tab defines who has access to the experiment and whether it is published to the intended audience.”

I think that will go a long way, 

One other non-nuclear option is hint text under opentexts. The only one I see that needs it at the moment is the Informed Consent field. Also, it would be good if the hint text on the Admin tab is some color other than red. The Basics tab uses light gray but that is hard to read. I think something with more contrast but not alarming would be good. Should I file a separate ticket for it?

Best,
Bob

**Comment by NickAraujo** [comment]
I think it's nice to leave this chain of discussion intact, so no additional ticket necessary.

I agree that some sort of persistent "Help" tab or link on all pages is a good idea.

Building on your idea Bob, this could be a dismissible sort of help text at the top of each page...

**Comment by BobEvans** [comment]
Update:

I finally got a chance to look at the pacostage site and yeah, there are a lot of little gray icons :-) The linking to the doc works well though. 

Before we throw away the icons, can we try one more pass with the following changes to your mock to make the icons not so disruptive.

Remove Icons
1) Remove the icon next to the experiment title - it isn’t meaningful
2) Remove the icon next to duration - ditto

Move placement of icons
3) Move the rest of the icons to the right side of their respective box, next to the expand/collapse icon. This will make them line up cleanly.

Change Icon
4) Invert the icon coloring from gray background and white text to dark gray text, transparent background and a thin, circular border around the figure.
5) Change the “i” to a question mark.

I would love to see how that looks. Are these 5 changes easy to do?

**Comment by BobEvans** [comment]
Update 2:

More thoughts about placement. 

1) Right now, some of the help icons are level with the label they address, and some are below the baseline of the label. On the right side of the page, it seems we would want them to be level with the label. 

2) One other option to try: keep them on the left but make them smaller and place them in superscript position respective to the label.

**Comment by ianspiro** [comment]
The idea is to see how it feels generally and there would be quite a few help icons either way. We need something that isn't overwhelming and is open-ended enough that we can put in as many tips as are necessary. I'll try the placement to the right with a subtler icon. 

What if the contextual help is something that the user has to enable globally for the site?

**Comment by BobEvans** [comment]
We should be able to limit it to a much smaller number of icons by only placing them at the top of sections. The definition of a "section” is rough, but something much more course-grained that attaches to a cohesive set of controls. 

Examples: 
the Triggers section gets one icon
the Inputs section gets one icon
Perhaps the Schedule dialog popup gets one icon to explain the types of schedules and their options. 

That last is a slightly different definition of “section” but it is still a fairly cohesive and distinct collection of controls that the user is focused on at one time.

To your last question, if user help were all over elements, then it would indeed be too noisy and we shouldn’t even allow them to do that with a global switch :-)

**Comment by ianspiro** [comment]
I updated pacostage to show the icons on the right and I think it does help. I didn't change any of the content yet since we're still prototyping but you can see the same ones from before under Groups. I threw in the Help checkbox just to see how it feels.

**Comment by BobEvans** [comment]
Ah. So, that is definitely an improvement.

Is it possible to put them inside the boxes instead of outside? They look a bit strange and more distracting floating outside of their respective areas. 
Moving it inside would definitely prompt getting rid of the top one since it would look pretty crazy next to the commands (DATA, STATS, COPY, DELETE)

The checkbox is clever, but, I think it introduces other issues. It is another moving part with not a lot of value, it’s a bit less helpful to hide contextual help behind a toggle and the word “help” displayed persistently on the screen should probably be reserved for the full help document window. I know we can change the label, but, I think a restrained use of contextual help icons persistently might be more helpful to the user. This is a hypothesis of course.

**Comment by ianspiro** [comment]
Updated the pacostage with a first attempt at the embedded, published Google doc. Visible on the Basics page. There's now a dedicated view for embedding with an iframe and some piping to translate a readable help id into the internal hyperlink. The links I used won't make any sense, just for showing the basic idea.

**Comment by ianspiro** [comment]
I talked to Jay. He's in favor of the help links in the sidebar with two caveats: 1) use them sparingly (i.e. only show conditional help link if conditional is checked) and 2) add a tooltip so the user is less startled when the link jumps them to a new tab.

3 examples here. https://pacostage.appspot.com

Turn on Conditional. Expand Advanced. Add a trigger. Links open up in a new tab on the embedded G doc but there is a bug. Sometimes the links cause the doc to jump the very end. I will investigate.

**Comment by NickAraujo** [comment]
I think this is looking much better! Great work!

-Nick

On Wed, Nov 25, 2015 at 4:09 PM, ianspiro <notifications@github.com> wrote:

> I talked to Jay. He's in favor of the help links in the sidebar with two
> caveats: 1) use them sparingly (i.e. only show conditional help link if
> conditional is checked) and 2) add a tooltip so the user is less startled
> when the link jumps them to a new tab.
>
> 3 examples here. https://pacostage.appspot.com
>
> Turn on Conditional. Expand Advanced. Add a trigger. Links open up in a
> new tab on the embedded G doc but there is a bug. Sometimes the links cause
> the doc to jump the very end. I will investigate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/paco/issues/1284#issuecomment-159763232>.
>



-- 
Nicholas Araujo | R@S <http://go/rats> Program Manager | araujon@google.com
<tamer@google.com> | C: 786-202-1782

**Comment by BobEvans** [comment]
It is looking much better and I like the way it works. 

Also, the help doc is looking good.

Thanks guys!

Bob
