### ISSUE TITLE
User Guide: Creating an Experiment

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1288]
Describe the various experimental features available in Paco.

**Comment by NickAraujo** [comment]
Could you please clarify which specific features are missing or how you would prefer this to be organized? The "Creating a Paco Experiment" section covers triggers, actions, inputs, experiment groups, and the options under "Advanced".

**Comment by BobEvans** [comment]
These were created a while ago and you have implemented them, so, I wanted to capture that fact and I thought you might like to close them :-)
