### ISSUE TITLE
Web UI: Input type: Change "Likert" to "Scale"

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1296]

**Comment by BobEvans** [comment]
Also change the steps label to Scale Steps or better yet, Number of Steps, or Steps

**Comment by ianspiro** [comment]
Where do I change this? Currently "likert" is the magic string used by the server so I still need to use that as the value of responseType. What about likert_smiley?

**Comment by NickAraujo** [comment]
Oh yes, let's find a better name for "likert_smiley"!

**Comment by BobEvans** [comment]
In general let’s change Likert to Scale and likert_smiley can be "5 point Smiley Scale” since it is not modifiable.

**Comment by ianspiro** [comment]
Ok, but for now, we need to use the same magic strings, right? I can map
them in my configuration { 'likert': 'Scale',...}

**Comment by NickAraujo** [comment]
Sounds good to me.

A bit more forward-looking: this is a case where a live preview (a la
Forms) would do wonders for intuitiveness.

-Nick

On Thu, Dec 10, 2015 at 1:23 PM, ianspiro <notifications@github.com> wrote:

> Ok, but for now, we need to use the same magic strings, right? I can map
> them in my configuration { 'likert': 'Scale',...}
>
> On Thu, Dec 10, 2015 at 1:08 PM, Bob Evans <notifications@github.com>
> wrote:
>
> > In general let’s change Likert to Scale and likert_smiley can be "5 point
> > Smiley Scale” since it is not modifiable.
> >
> >
> > > On Dec 10, 2015, at 11:55 AM, NickAraujo <notifications@github.com>
> > wrote:
> > >
> > > Oh yes, let's find a better name for "likert_smiley"!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/paco/issues/1296#issuecomment-163749782>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/paco/issues/1296#issuecomment-163753442>.
>



-- 
Nicholas Araujo | R@S <http://go/rats> Program Manager | araujon@google.com
<tamer@google.com> | C: 786-202-1782

**Comment by BobEvans** [comment]
Yes, the constants are still the constants in the schema so we still need to create the schema using those.
