### ISSUE TITLE
Web UI: Move Informed Consent, Extra Types of Data Collection, & Phone Details to the Basics Tab

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1298]
The tabs follow the conversation of the user  in order of exposure, so, to help researchers, move informed consent, Data Collection Declarations, & Phone Details onto the basics tab before the post-join install instructions to make the flow match the user flow better.

**Comment by NickAraujo** [comment]
Merged with [issue 1358](https://github.com/google/paco/issues/1358).
