### ISSUE TITLE
Web UI: Action popup accepts negative values

### ISSUE THREAD

**Issue by NickAraujo** [google/paco#1304]
A user can exit the Action popup after entering negative values for timeouts, snooze repeats, and snooze time.

![image](https://cloud.githubusercontent.com/assets/15365617/10894676/fb676506-8164-11e5-9fc2-d73b245e010b.png)

**Comment by ianspiro** [comment]
Is zero a valid Timeout value?

**Comment by BobEvans** [comment]
not currently. It has to be a positive value.

**Comment by ianspiro** [comment]
Which of these are >= 0 vs > 0?

Timeout
Delay
Snooze Time

**Comment by ianspiro** [comment]
Easy to fix if I can get clarification on the inclusivity of the inequality.

**Comment by BobEvans** [comment]
Hi Ian,

They are all > 0

Thanks,
Bob
