### ISSUE TITLE
Web UI: Bottom of Data report screen is clipped and not visible

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1309]
The actions are clipped at half letter height at the bottom of the screen (in Chrome) on the data screen. See screenshot.

**Comment by BobEvans** [comment]
![screen shot 2015-11-04 at 9 10 19 pm](https://cloud.githubusercontent.com/assets/1422459/10960317/a460702e-8338-11e5-8691-5f317f8de97d.png)

**Comment by BobEvans** [comment]
This happens when zooming out (cmd-minus) to see more columns at once

**Comment by BobEvans** [comment]
Received another report from an external user that they can't see the download button. Asking for a screenshot. Will attach when received.

**Comment by ianspiro** [comment]
I know why the bug is happening so I don't need the screenshot. It's when the user doesn't have a trackpad and extra scroll bars appear. I'm still thinking about the fix.
