### ISSUE TITLE
Web UI: Improve data analysis capabilities

### ISSUE THREAD

**Issue by NickAraujo** [google/paco#1330]
This is a shell for a larger, more complex issue. Please comment with related feature requests and use cases.

Here's the background:

Data analysis is an important part of the lifecycle of any Paco study. Paco currently provides raw data that requires additional manipulation by a researcher before it can be interpreted. The usability and usefulness of Paco can be improved by making data analysis easier when possible. Similar products offer solutions for this, and researchers may have come to expect more than raw data.

Some ideas:

* Reporting data by data name rather than data index name to make it easier to parse (e.g., for a Yes | No question, report "Yes" instead of "1")
* Create visualizations for closed-choice questions in addition to raw data (a la Google Forms)
* Create summary stats and/or visualizations for open-ended questions, e.g., based on keyword frequency (a la Survey Monkey, text.it), tagging (a la dScout, QualVu), etc.

**Comment by mhadjimichael** [comment]
What about something like Microsoft Excel's Pivot Tables/Data cubes?

**Comment by BobEvans** [comment]
Please create separate issues for each of the actual feature suggestions and close this ticket. Please also post a comment back to the url for this ticket to keep the context. Thanks!
