### ISSUE TITLE
Web UI: Likert steps should be capped

### ISSUE THREAD

**Issue by NickAraujo** [google/paco#1356]
Currently, Paco only supports likert scales with up to 9 steps. The UI should not allow a user to enter more than this limit. A capped integer field (or a dropdown) would work here.

![image](https://cloud.githubusercontent.com/assets/15365617/11708514/d92145c0-9ec4-11e5-9b0c-d98c12813cba.png)

**Comment by ianspiro** [comment]
Fixed. Demo available on pacostage.
