### ISSUE TITLE
iOS: Clarify error message when stopping experiment

### ISSUE THREAD

**Issue by NickAraujo** [google/paco#1449]
The current error message:

Are you sure?
All your data will be deleted permanently with this experiment.

...has been interpreted as meaning that all of a participant's collected data will be deleted, when, in reality, it will be deleted from the phone but will remain available online (to both participant and experiment admins).

Some clearer options might be:

Are you sure? 
Deletes this experiment's data from this device (but not from pacoapp.com).

Are you sure? 
You'll permanently delete this experiment's data from this device. You (and experiment admins) can still access the data on pacoapp.com.

**Comment by tuvalusoftware** [comment]
No relevant to version of paco under development
