### ISSUE TITLE
iOS - experiment Invitations screen should have apple slash icon for apple incompatible experiments

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1485]
This might be the placeholder for iOS compatible or not.

If so, we already have a graphic for this that should be at the leftmost of each list entry.

<img width="319" alt="screen shot 2016-08-03 at 1 34 10 am" src="https://cloud.githubusercontent.com/assets/1422459/17359226/89fe3de8-591a-11e6-89e7-39e0f20f2208.png">

**Comment by BobEvans** [comment]
Also,
 the row should show organization, if it exists, otherwise remove the comma and show just the Contact Email if it exists. If that does not exist, show the creator email.

**Comment by tuvalusoftware** [comment]
Table cell needs formatting and expanded height but the icon is correct at this point
