### ISSUE TITLE
Subjects are automatically being automatically logged out on iOS only

### ISSUE THREAD

**Issue by wupeggy** [google/paco#1526]
I've tested my study with iOS and Android phones and all my iOS subjects are getting their gmail accounts automatically logged out, and they have to re-login. Please help!

**Comment by BobEvans** [comment]
Hi Peggy,

I am sorry this is happening. We have just seen this issue with other studies as well. We are working to identify the cause of the problem. I will keep you posted.

Best,
Bob

**Comment by wupeggy** [comment]
Thanks Bob. Any ideas about when this might be addressed?  We're getting ready for our study and would like to contribute to fixing this problem as well if we could.

**Comment by BobEvans** [comment]
This issue has been fixed in the latest iOS release - 1.1.8.1
