### ISSUE TITLE
Ability to prevent ad-hoc self-reports?

### ISSUE THREAD

**Issue by wupeggy** [google/paco#1527]
Hello, I'm trying to do an ESM where subjects can ONLY subject a survey when I send a randomly timed notification and they cannot adhoc complete a survey without an associated notification. Is that possible? Thanks very much!

**Comment by NickAraujo** [comment]
Hi Peggy,

This is currently not enforced in the UI. We're aware of the feature request (#1432), but it is unfortunately not currently on our roadmap. For the time being, I'd suggest emphasizing this when onboarding participants, perhaps incentivizing them by linking their incentives to the % of timed notifications they respond to.

-Nick

**Comment by BobEvans** [comment]
Hi Peggy

In addition to what Nick said, if it is at least somewhat helpful you can see that self reports are different in the data set. So you can drop all the self reports from your analysis.

The self reports will have a value for the column “responseTime”, but, not for the column, “scheduledTime”. Signaled responses will have a “scheduledTime”.

Hope that helps until we get around to this feature.

Best,
Bob

**Comment by wupeggy** [comment]
Hi Bob and Nick,
Thanks so much for your response! We'll use the work around.
Best,
Peggy

**Comment by BobEvans** [comment]
Hi Peggy,

Let us know how it works out.

Best,
Bob
