### ISSUE TITLE
iOS: corner case of min buffer is 0

### ISSUE THREAD

**Issue by yimingcheung** [google/paco#655]
https://github.com/google/paco/issues/933

All random numbers have to be sorted in this case:
+ (NSArray*)randomIntegersInRange:(NSUInteger)rangeNumber
                    numOfIntegers:(NSUInteger)numOfIntegers
                        minBuffer:(NSUInteger)minBuffer {

**Comment by BobEvans** [comment]
Obsoleted in v4 by use of new scheduler.
