### ISSUE TITLE
Server Bug: viewData screen shows two photos if varname is duplicate for a photo and non-photo item

### ISSUE THREAD

**Issue by yimingcheung** [google/paco#741]
1. Shouldn't we already prevent users to create two inputs with the same variable name?
2. If two inputs have exactly the same variable name, it seems like when you viewData, the two inputs will have the same answers, even if one of them is not answered actually. So the guess is that server is using variable name as the key to store or access data, instead of inputId.

**Comment by BobEvans** [comment]
obsolete
